services:
  builder:
    build: .
    working_dir: /workdir
    privileged: true
    user: "0:0"
    env_file: .env
    environment:
      BUILDER_CONTAINER: "1"
      HOST_UID: ${HOST_UID:?HOST_UID is required}
      HOST_GID: ${HOST_GID:?HOST_GID is required}
    volumes:
      - ./workdir:/workdir
      - .:/builder:ro
      - ${BUILD_LOCAL}:${BUILD_LOCAL}
      - ${BUILD_JAHITAN_PATH}:${BUILD_JAHITAN_PATH}
